hw1.data= read.csv("desktop/WCAS.ECONOMETRICS/moneyball.training.data.csv")
head(hw1.data)
tail(hw1.data)
install.packages("psych")
library(psych)
describe(hw1.data)
head(hw1.data)
na.cols <- which(colSums(is.na(hw1.data)) > 0)
nrow(hw1.data)
sort(colSums(sapply(hw1.data[na.cols], is.na)), decreasing = TRUE)
length(na.cols)
length(hw1.data$TARGET_WINS)
length(hw1.data$TEAM_BATTING_H)
hist(hw1.data$TEAM_BATTING_HBP, main='Batters Hit By Pitch')
install.packages("moments")
library(moments)
skewness(hbp, na.rm = TRUE)
hist(hw1.data$TEAM_BASERUN_CS, main=" Runners Caught Stealing")
runners.caught=hw1.data$TEAM_BASERUN_CS
skewness(runners.caught, na.rm=TRUE)
hist(hw1.data$TEAM_FIELDING_DP, main="Douple Plays Converted")
skewness(hw1.data$TEAM_FIELDING_DP, na.rm = TRUE)
hist(hw1.data$TEAM_BASERUN_SB, main="Stolen Bases")
skewness(hw1.data$TEAM_BASERUN_SB, na.rm = TRUE)
hist(hw1.data$TEAM_BATTING_SO, main="Team Strikeouts")
skewness(hw1.data$TEAM_BATTING_SO, na.rm = TRUE)
hist(hw1.data$TEAM_PITCHING_SO, main="Batters Strucken Out")
skewness(hw1.data$TEAM_PITCHING_SO, na.rm = TRUE)
hw1.data$TEAM_BATTING_HBP=ifelse(is.na(hw1.data$TEAM_BATTING_HBP),mean(hw1.data$TEAM_BATTING_HBP,na.rm=T),hw1.data$TEAM_BATTING_HBP)
hw1.data$TEAM_FIELDING_DP=ifelse(is.na(hw1.data$TEAM_FIELDING_DP),mean(hw1.data$TEAM_FIELDING_DP,na.rm=T),hw1.data$TEAM_FIELDING_DP)
hw1.data$TEAM_BATTING_SO=ifelse(is.na(hw1.data$TEAM_BATTING_SO),mean(hw1.data$TEAM_BATTING_SO,na.rm=T),hw1.data$TEAM_BATTING_SO)
hw1.data$TEAM_BASERUN_CS=ifelse(is.na(hw1.data$TEAM_BASERUN_CS),median(hw1.data$TEAM_BASERUN_CS,na.rm=T),hw1.data$TEAM_BASERUN_CS)
hw1.data$TEAM_BASERUN_SB=ifelse(is.na(hw1.data$TEAM_BASERUN_SB),median(hw1.data$TEAM_BASERUN_SB,na.rm=T),hw1.data$TEAM_BASERUN_SB)
hw1.data$TEAM_PITCHING_SO=ifelse(is.na(hw1.data$TEAM_PITCHING_SO),median(hw1.data$TEAM_PITCHING_SO,na.rm=T),hw1.data$TEAM_PITCHING_SO)
install.packages("psych")
library(psych)
describe(hw1.data)
install.packages("ResourceSelection")
par(mfrow=c(2,2))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_BATTING_SO)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_BATTING_SO))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_BATTING_SO))
par(mfrow=c(2,2))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_BATTING_3B)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_BATTING_3B))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_BATTING_3B))
par(mfrow=c(2,2))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_BASERUN_SB)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_BASERUN_SB))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_BASERUN_SB))
par(mfrow=c(2,2))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_BASERUN_CS)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_BASERUN_CS))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_BASERUN_CS))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_BATTING_HBP)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_BATTING_HBP))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_BATTING_HBP))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_PITCHING_H)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_PITCHING_H))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_PITCHING_H))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_PITCHING_BB)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_PITCHING_BB))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_PITCHING_BB))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_PITCHING_SO)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_PITCHING_SO))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_PITCHING_SO))
plot(hw1.data$TARGET_WINS~hw1.data$TEAM_FIELDING_DP)
plot(hw1.data$TARGET_WINS~sqrt(hw1.data$TEAM_FIELDING_DP))
plot(hw1.data$TARGET_WINS~log(hw1.data$TEAM_FIELDING_DP))
par(mfrow=c(1,1))
plot(log(hw1.data$TARGET_WINS)~(hw1.data$TEAM_BATTING_3B))
hw1.data["bases"]= (hw1.data$TEAM_BATTING_H+hw1.data$TEAM_BATTING_BB+hw1.data$TEAM_BASERUN_SB+hw1.data$TEAM_BATTING_HBP/)


hw1.data["log.3B"]=hw1.data$TEAM_BATTING_3B
hw1.data["log.hits.allwd"]= hw1.data$TEAM_PITCHING_H
hw1.data["log.so"]=hw1.data$TEAM_BATTING_SO
hw1.data.train= hw1.data[,-c(5,8,12)]
head(hw1.data.train)
describe(hw1.data)
lmMod <- lm(hw1.data.train$TARGET_WINS ~. , data = hw1.data.train)
summary(lmMod)
selectedMod <- step(lmMod)
summary(selectedMod)
par(mfrow=c(1,1))
plot(lmMod$residuals, main="RESIDUALS: MODEL 1")
qqnorm(lmMod$residuals)
qqline(lmMod$residuals)
hist(lmMod$residuals)
summary(lmMod)
lmMod <- lm(hw1.data.train$TARGET_WINS ~. , data = hw1.data.train)
summary(lmMod)


lmMod2=lm(hw1.data.train$TARGET_WINS ~ hw1.data.train$TEAM_BATTING_H+hw1.data.train$TEAM_BATTING_2B+hw1.data.train$TEAM_BASERUN_SB+hw1.data.train$TEAM_PITCHING_SO+hw1.data$TEAM_FIELDING_E+hw1.data$TEAM_FIELDING_DP+hw1.data.train$log.3B+hw1.data.train$log.hits.allwd+hw1.data.train$log.so)
summary(lmMod2)
lmMod3 <- step(lmMod)
summary(lmMod3)
all_vifs <- VIF(lmMod3)
print(all_vifs)
signif_all <- names(all_vifs)
lmMod4= lm(hw1.data.train$TARGET_WINS~ hw1.data.train$TEAM_BATTING_H +hw1.data.train$TEAM_BATTING_2B+hw1.data.train$TEAM_BATTING_BB+hw1.data.train$TEAM_BASERUN_SB+hw1.data.train$TEAM_PITCHING_SO+hw1.data.train$TEAM_FIELDING_E+hw1.data.train$TEAM_FIELDING_DP+hw1.data.train$log.3B+hw1.data.train$log.hits.allwd)
summary(lmMod4)



test=read.csv("desktop/WCAS.ECONOMETRICS/mball.test.csv")
na.cols <- which(colSums(is.na(test)) > 0)
sort(colSums(sapply(test[na.cols], is.na)), decreasing = TRUE)
test$TEAM_BATTING_HBP=ifelse(is.na(test$TEAM_BATTING_HBP),mean(test$TEAM_BATTING_HBP,na.rm=T),test$TEAM_BATTING_HBP)
test$TEAM_FIELDING_DP=ifelse(is.na(test$TEAM_FIELDING_DP),mean(test$TEAM_FIELDING_DP,na.rm=T),test$TEAM_FIELDING_DP)
test$TEAM_BATTING_SO=ifelse(is.na(test$TEAM_BATTING_SO),mean(test$TEAM_BATTING_SO,na.rm=T),test$TEAM_BATTING_SO)
test$TEAM_BASERUN_CS=ifelse(is.na(test$TEAM_BASERUN_CS),median(test$TEAM_BASERUN_CS,na.rm=T),test$TEAM_BASERUN_CS)
test$TEAM_BASERUN_SB=ifelse(is.na(test$TEAM_BASERUN_SB),median(test$TEAM_BASERUN_SB,na.rm=T),test$TEAM_BASERUN_SB)
test$TEAM_PITCHING_SO=ifelse(is.na(test$TEAM_PITCHING_SO),median(test$TEAM_PITCHING_SO,na.rm=T),test$TEAM_PITCHING_SO)
describe(test)
y=hw1.data$TARGET_WINS[1:259]
y
test["log.3B"]<- log(test$TEAM_BATTING_3B)
test["log.hits.allwd"]<- log(test$TEAM_PITCHING_H)
test["log.so"]= log(test$TEAM_BATTING_SO)
head(test)
test2= test[,-c(4,7,11)]
head(test2)
outcome=hw1.data.train$TARGET_WINS[1:259]
prediction1 <- predict(lmMod, test2)
prediction1
RMSE(outcome, prediction1)
prediction2 <- predict(lmMod2, test2)
prediction2
prediction2 <- predict(lmMod2, test2)
prediction2
prediction3 <- predict(lmMod3, test2)
prediction3=prediction3[1:259]
prediction3
prediction4 <- predict(lmMod4, test2)
prediction4

cbind(AIC(lmMod,lmMod2,lmMod3,lmMod4))
cbind(BIC(lmMod,lmMod2,lmMod3,lmMod4))
setwd("desktop/WCAS>ECONOMETRICS")



write.csv(prediction1,file= "prediction1.csv", row.names = F)
write.csv(prediction2,file= "prediction2.csv", row.names = F)
write.csv(prediction3,file= "prediction3.csv", row.names = F)
write.csv(prediction4,file= "prediction4.csv", row.names = F)



